### PR TITLE
Fix Django 2

### PR DESCRIPTION
**Pull request by btoueg**
Only fixes import issues (otherwise untested)

### CODE REVIEW

**Comment by btoueg** [comment]
Haha, I've should have run the tests locally...

I'll fix the url issues in the coming days :)

**Comment by kencochrane** [comment]
@btoueg how is it coming along? I’m be doing a release in the next day or so, if this PR is finished before then, I can include it.

**Comment by btoueg** [comment]
Since https://github.com/kencochrane/django-defender/pull/106/files, it just needs a coveralls re-trigger

**Comment by btoueg** [comment]
I did my best... 26 failing tests

Looks like Django 2.0 does not like this way to mock login in tests https://github.com/kencochrane/django-defender/blob/master/defender/tests.py#L66-L70

I'm not familiar with such pattern, and don't understand the need for such complexity.

How would you like to proceed?

**Comment by kencochrane** [comment]
@btoueg Thanks for taking the time to look at this. I don't have time right now to investigate, I'm about to leave on vacation, but I'll look at it when I get back. 

In the meantime if anyone else has some time and knows the answer, feel free to post it here.

**Comment by MattBlack85** [comment]
@btoueg I suspect this is something related to the middlewares, if you put a
```@override_settings(MIDDLEWARE=[
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
])```
on the testcase that error go and other errors appear. I agree tho, that the way of testing login should be refactored to something simpler

**Comment by kencochrane** [comment]
Looks like this comment would fix this PR as well: https://github.com/kencochrane/django-defender/pull/126#issuecomment-432243970

**Comment by kencochrane** [comment]
closing since #126 fixed the same thing.

**Pull request closed without merging**
