### PR TITLE
Match Django Axes behavior on locked users

### PR DESCRIPTION
**Pull request by marcusmartins**
**For discussion**:
Match how Django Axes locks out users based on IP and username.
Also adds additional test to cover the functionality as the previous
tests were not verifying usernames.

Reference:
https://github.com/django-pci/django-axes/blob/6bd5a50cb83b980c7ea60f45ee5e1c7d8543746b/axes/decorators.py#L219

### CODE REVIEW

**Comment by kencochrane** [comment]
I'm still undecided on this. I like how it duplicates the axes functionality, but the more I think about it, I think the axes functionality is flawed when a Bot net brute force attempt is used, since it would allow way more attempts in a username, since it would allow x number per IP.

Willing to talk about this more. What do others think?

/cc @shin-

**Comment by marcusmartins** [comment]
Yeah, I decided to open the PR as I noticed the tests were not covering the block by username functionality as usernames were always being randomized.

**Comment by kencochrane** [comment]
OK, then maybe keep the unit test changes, and keep it the way we have it now?

**Comment by shin-** [comment]
I personally think `or` makes more sense.

**Pull request closed without merging**
