### PR TITLE
initial commit, adding admin pages to manage blocked users

### PR DESCRIPTION
**Pull request by kencochrane**
This is the start of a PR that will be used to add the Admin pages for managing blocked users. Ideally someone can use the django admin to see who is blocked (ip or username) and remove the block manually from the admin.

Still a work in progress, still need to test, submitting for early review.

/cc @shin- @marcusmartins

### CODE REVIEW

**Comment by marcusmartins** [comment]
I think it will be nice to fix this issue #26 before merging this in.

I will try to submit a PR soon.

**Comment by kencochrane** [comment]
marcus, I can fix it right now, I'm in there anyway, should be quick.

Ken

**Comment by marcusmartins** [comment]
Thanks!

**Comment by kencochrane** [comment]
Here are some examples of what the admin looks like.

admin_1
admin_2

**Pull request merged**
