### PR TITLE
Feature update Python and Django versions

### PR DESCRIPTION
**Pull request by fr0mhell**
* remove Python 3.3
* remove Django 1.8-1.10
* add Celery v4
* update travis config
* update admin URL

### CODE REVIEW

**Comment by bj00rn** [comment]
@kencochrane @fr0mhell looks like tests are passing now.

merge?

**Comment by kencochrane** [comment]
Looks good, thank you!

**Comment by bj00rn** [comment]
🥇 Thanks! @kencochrane can you release 0.6 as well?

**Comment by kencochrane** [comment]
@bj00rn done: https://pypi.org/project/django-defender/

**Pull request merged**
